import { AppData } from '../types';

export const initialData: AppData = {
  version: '1.0.0',
  lastUpdated: '2026-06-15',
  properties: [
    {
      id: 'docta',
      name: 'Inmueble Docta',
      address: 'Docta',
      city: 'Córdoba',
      country: 'AR',
      role: 'owned_rented_out',
      rentAmount: 1100,
      rentCurrency: 'USD',
      rentDueDay: 1,
      accounts: [
        { service: 'EPEC', accountNumber: '306409101' },
        { service: 'Aguas Cordobesas', accountNumber: '784319' },
        { service: 'Gas Ecogas', accountNumber: '2302536' },
      ],
    },
    {
      id: 'ayres',
      name: 'Inmueble Ayres',
      address: 'Ayres - Unquillo',
      city: 'Córdoba',
      country: 'AR',
      role: 'owned_rented_out',
      rentAmount: 800,
      rentCurrency: 'USD',
      rentDueDay: 1,
      accounts: [
        { service: 'Municipalidad Unquillo', accountNumber: '042898' },
        { service: 'Internet Sierras Chicas', accountNumber: '', notes: 'sierraschicaswifi.com.ar' },
      ],
    },
    {
      id: 'nva-cba',
      name: 'Inmueble Nueva Córdoba',
      address: 'Nueva Córdoba',
      city: 'Córdoba',
      country: 'AR',
      role: 'owned_vacant',
      accounts: [
        { service: 'Rentas Córdoba', accountNumber: '110123395646' },
        { service: 'Municipalidad Córdoba', accountNumber: '040903405400002' },
        { service: 'EPEC', accountNumber: '706240', notes: 'Contrato 0077006405' },
        { service: 'Aguas Cordobesas', accountNumber: '370670', notes: 'Responsable: Leandro' },
        { service: 'Gas Ecogas', accountNumber: '21163280' },
      ],
    },
    {
      id: 'pardo',
      name: 'Inmueble Pardo',
      address: 'Pardo',
      city: 'Lima',
      country: 'PE',
      role: 'owned_rented_out',
      rentAmount: 2720,
      rentCurrency: 'PEN',
      rentDueDay: 1,
      accounts: [],
    },
    {
      id: 'vargas-machuca',
      name: 'Dpto. Vargas Machuca',
      address: 'Vargas Machuca',
      city: 'Lima',
      country: 'PE',
      role: 'renting',
      rentAmount: 900,
      rentCurrency: 'USD',
      rentDueDay: 1,
      accounts: [],
    },
  ],
  transactions: [],
  vencimientos: [
    {
      id: 'v1',
      propertyId: 'docta',
      name: 'Expensas Docta',
      category: 'Expensas',
      amount: 220000,
      currency: 'ARS',
      dueDate: '2026-06-10',
      paid: true,
      paidDate: '2026-06-09',
      recurring: true,
      recurringDayOfMonth: 10,
    },
    {
      id: 'v2',
      propertyId: 'docta',
      name: 'EPEC Docta',
      category: 'Electricidad',
      amount: 80000,
      currency: 'ARS',
      dueDate: '2026-06-20',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 20,
    },
    {
      id: 'v3',
      propertyId: 'docta',
      name: 'Aguas Cordobesas Docta',
      category: 'Agua',
      amount: 45000,
      currency: 'ARS',
      dueDate: '2026-06-25',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 25,
    },
    {
      id: 'v4',
      propertyId: 'docta',
      name: 'Gas Docta',
      category: 'Gas',
      amount: 35000,
      currency: 'ARS',
      dueDate: '2026-06-28',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 28,
    },
    {
      id: 'v5',
      propertyId: 'docta',
      name: 'Rentas Córdoba Docta',
      category: 'Impuestos',
      amount: 50000,
      currency: 'ARS',
      dueDate: '2026-06-15',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 15,
    },
    {
      id: 'v6',
      propertyId: 'ayres',
      name: 'Expensas ordinarias Ayres',
      category: 'Expensas',
      amount: 170000,
      currency: 'ARS',
      dueDate: '2026-06-10',
      paid: true,
      paidDate: '2026-06-09',
      recurring: true,
      recurringDayOfMonth: 10,
    },
    {
      id: 'v7',
      propertyId: 'ayres',
      name: 'Expensas extraordinarias Ayres',
      category: 'Expensas',
      amount: 175000,
      currency: 'ARS',
      dueDate: '2026-06-10',
      paid: false,
      recurring: false,
    },
    {
      id: 'v8',
      propertyId: 'ayres',
      name: 'Municipalidad Unquillo',
      category: 'Impuestos',
      amount: 25000,
      currency: 'ARS',
      dueDate: '2026-06-20',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 20,
    },
    {
      id: 'v9',
      propertyId: 'ayres',
      name: 'Internet Sierras Chicas',
      category: 'Internet',
      amount: 20000,
      currency: 'ARS',
      dueDate: '2026-06-05',
      paid: true,
      paidDate: '2026-06-04',
      recurring: true,
      recurringDayOfMonth: 5,
    },
    {
      id: 'v10',
      propertyId: 'nva-cba',
      name: 'Expensas Nueva Cba',
      category: 'Expensas',
      amount: 300000,
      currency: 'ARS',
      dueDate: '2026-06-10',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 10,
    },
    {
      id: 'v11',
      propertyId: 'nva-cba',
      name: 'EPEC Nueva Cba',
      category: 'Electricidad',
      amount: 60000,
      currency: 'ARS',
      dueDate: '2026-06-20',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 20,
    },
    {
      id: 'v12',
      propertyId: 'nva-cba',
      name: 'Aguas Cordobesas Nueva Cba',
      category: 'Agua',
      amount: 48000,
      currency: 'ARS',
      dueDate: '2026-06-25',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 25,
    },
    {
      id: 'v13',
      propertyId: 'nva-cba',
      name: 'Gas Nueva Cba',
      category: 'Gas',
      amount: 45000,
      currency: 'ARS',
      dueDate: '2026-06-28',
      paid: false,
      recurring: true,
      recurringDayOfMonth: 28,
    },
    {
      id: 'v14',
      propertyId: 'vargas-machuca',
      name: 'Alquiler Vargas Machuca',
      category: 'Alquiler',
      amount: 900,
      currency: 'USD',
      dueDate: '2026-06-01',
      paid: true,
      paidDate: '2026-06-01',
      recurring: true,
      recurringDayOfMonth: 1,
    },
  ],
  exchangeRates: [
    {
      id: 'er1',
      date: '2026-06-15',
      USD_ARS: 1150,
      USD_PEN: 3.72,
    },
  ],
  budgetCategories: [
    { id: 'bc1', name: 'Alquiler (Vargas Machuca)', monthlyBudget: 900, currency: 'USD' },
    { id: 'bc2', name: 'Alimentación', monthlyBudget: 1200, currency: 'PEN' },
    { id: 'bc3', name: 'Universidad', monthlyBudget: 1200, currency: 'PEN' },
    { id: 'bc4', name: 'Restaurantes', monthlyBudget: 730, currency: 'PEN' },
    { id: 'bc5', name: 'Seguros', monthlyBudget: 1720, currency: 'PEN' },
    { id: 'bc6', name: 'Transporte', monthlyBudget: 620, currency: 'PEN' },
    { id: 'bc7', name: 'Servicios Dpto', monthlyBudget: 830, currency: 'PEN' },
    { id: 'bc8', name: 'Gym', monthlyBudget: 450, currency: 'PEN' },
    { id: 'bc9', name: 'Entretenimiento', monthlyBudget: 358, currency: 'PEN' },
    { id: 'bc10', name: 'Suscripciones', monthlyBudget: 113, currency: 'PEN' },
    { id: 'bc11', name: 'Otros', monthlyBudget: 200, currency: 'PEN' },
  ],
  monthlyActuals: [],
};
